### ISSUE TITLE
Update Implementations Links

### ISSUE THREAD

**Issue by RichardLitt** [jbenet/multistream#11]
Neither of the implementations listed [here](https://github.com/multiformats/go-multistream-select) exist:

```
# Implementations

- [js-multistream-select](https://github.com/diasdavid/js-multistream-select) - JavaScript Implementation
- [go-multistream-select](https://github.com/whyrusleeping/go-multistream-select) - Go Implementation
- [mss-nc](https://github.com/whyrusleeping/mss-nc) - multistream-select netcat written in Go
```

Where are they now? Where should they be?

**Comment by whyrusleeping** [comment]
I think theyre in the multiformats org

**Comment by whyrusleeping** [comment]
Ah, no:

https://github.com/multiformats/go-multistream
https://github.com/whyrusleeping/mss-nc

**Comment by daviddias** [comment]
@RichardLitt seems like you already fixed this one, thank you :)
